### ISSUE TITLE
Hero Siege Stats opens but does not work.

### ISSUE THREAD

**Issue by Malk4viano** [GuilhermeFaga/hero-siege-stats#2]
Hi, first of all, thanks for the app!

I'm using the app on Windows 11 64bit, and I have Npcap 1.79 installed.

Hero Siege Stats opens, the time counter works, but everything else doesn't.

I've tried running as admin, but the same problem occurs.

Anything I could be doing wrong?

**Comment by GuilhermeFaga** [comment]
Could be related to the server IP, are you playing on Asia? If not, the IP of your server could have changed.

**Comment by GuilhermeFaga** [comment]
@Malk4viano could you try again with the new version?

**Comment by Malk4viano** [comment]
All working fine after the new update!

Very nice update btw! Thx mate!

And i forgot to mention last time: I'm playing in Odyssey mode. :)
