### ISSUE TITLE
Scrap more things by packets

### ISSUE THREAD

**Issue by Runo231** [GuilhermeFaga/hero-siege-stats#3]
Is there any option to obtain information on the packages to obtain the items or market information? or any relevant information such as chaos tower or shadow realm?

**Comment by GuilhermeFaga** [comment]
**Market information**
I was not successful in getting market information, and they don't have any API for it too.

**Chaos Tower**
When I was actively developing the app, Chaos Tower was not in the game yet.

**Shadow Realm**
I did in fact, not search for any info regarding the Shadow Realm. Could or not be data about it.
