### ISSUE TITLE
Only the time and the xp counters works

### ISSUE THREAD

**Issue by Umeryth** [GuilhermeFaga/hero-siege-stats#4]
Hello how are you? I hope well. Firstly I would like to thank you for the project! It's an incredible idea. 

And as for my problem, unfortunately I did everything I could to make the software work correctly (I play on Mevius (America), I set it to start as an administrator, I use Windows 11 (64 bits) and I'm using Npcap 1.79), However, it presents the following problems:

• Only xp and time played counters are counted.
• The xp counter is locked from the moment you change maps, making it necessary to reopen the software.
• the other counters don't work no matter what I try or do, including the drop counter, the gold counter, and finally the mail counter.

In this case I would like to know how to proceed, if it could be something incorrigible in this current version or if there was something I could do, thank you in advance for your patience and for the development of this project, I believe it will be of great help to the entire community.

**Comment by GuilhermeFaga** [comment]
Hi @Umeryth, thanks for the feedback!

As for why it isn´t working, it would be necessary to validate the game requests with WireShark and make the apropriate changes.

As the game updates the format of the requests are bound to change.

The best way is to filter the requests in WireShark with your server IP and make a few actions in game then store the requests that appear.

If you do this I can help.

**Comment by GuilhermeFaga** [comment]
@Umeryth the app has a new version, care to test it?
